# Generated by Django 4.0.5 on 2022-11-19 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybasemodel',
            name='company_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 05999999999', regex='^(977)\\d{10}$')]),
        ),
    ]
