# Generated by Django 4.0.5 on 2023-03-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_companybasemodel_company_number'),
        ('company', '0002_initial'),
    ]

    operations = [
    ]
