# Generated by Django 4.0.5 on 2022-11-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('reg_number', models.BigIntegerField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('sub_total', models.BigIntegerField(blank=True, null=True)),
                ('main_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_invoice', to='invoice.maininvoice')),
            ],
        ),
    ]
